### ISSUE TITLE
Touch Screen Compatability?

### ISSUE THREAD

**Issue by emgbeeker** [godswearhats/jquery-ui-rotatable#12]
Rotatable is completely awesome thank you for your efforts. I'm trying to use the plugin for a web app that's destined for an iPad. Testing on desktop browsers works perfectly. Unfortunately, i'm not able to get rotation to work on the iPad. When I tap and drag on the rotation handle, nothing happens. I tried the obvious replacement of mouse triggers with touch triggers (touchstart, touchmove and touchend)...this did not do the trick. Any insight you can provide is very much appreciated.

Thanks again

**Comment by godswearhats** [comment]
I'm not able to reproduce this any longer. Please re-open if this is still a problem.

**Comment by mgmbh** [comment]
Hi godswearhats,

I still can reproduce this by simply adding jquery.ui.touch-punch.js to your demo and open the file on my smartphone. The examples with draggable activated work, the standalone rotatables don't. Resizable doesn't seem to have an impact, it has to be draggable.

Seems like you can work around this issue by simply making the element draggable anyway and set the handle to .ui-rotatable-handle. This will "activate" the handle for touch-input. The element itself won't be draggable since rotatable will overwrite the handle events, I guess.
```
$('#rotate').draggable({handle: ".ui-rotatable-handle"}).rotatable(params);
```
I hope this will help someone.

Nice plugin by the way!

**Comment by godswearhats** [comment]
Thanks for the workaround. I think the real fix is likely there somewhere, but it seems to be beyond my skills :-)

**Comment by Snorvarg** [comment]
Hi, 
maybe I have found something on this topic. I tried to make the rotating button work with a similar setup as described here, and have the same issue on iPad: The button is not working. 

So I created a 'stand alone' button which simulates the mouse event by translating the event.touches[0].clientX into event.clientX, and then I call the corresponding 'startRotate', 'rotateElement' and 'stopRotate'. It works.

This code snippet expect a div with id "rotatableProt", and a previous call to setup rotatable. 

```javascript
<div 
	style="border: 1px solid black; background-color: #ccddee; height: 50px;"
	ontouchstart="onTS(event);"
	ontouchmove="onTM(event);"
	ontouchend="onTE(event);"
>Rotate</div>
<script>
	function onTS(event)
	{
		// console.log(event);

		// Simulate mouse event.
		event.buttons = 1;
		event.clientX = event.touches[0].clientX;
		event.clientY = event.touches[0].clientY;
										
		$('#rotatableProt').rotatable("startRotate", event);
	}
	function onTM(event)
	{
		// console.log(event);

		// Simulate mouse event.
		event.buttons = 1;
		event.clientX = event.touches[0].clientX;
		event.clientY = event.touches[0].clientY;
		
		$('#rotatableProt').rotatable("rotateElement", event);
	}
	function onTE(event)
	{
		$('#rotatableProt').rotatable("stopRotate", event);
	}
</script>
```

I made this in order to understand why rotatable is not working on iPad. Now when I see mgmbh's comment above, I will give his idea a try.

**Comment by twinkleminds** [comment]
Hi,

Because the plugin don't handle the touchstart, touchmove and touchend events, is not working correctly, not even with plugins like touch punch. At least not for me.
I have added those events to the plugin, with some minor amends and for me is working perfectly now.
Will suggest a pull request when I get a sec.
Until then you can take it and try it from dropbox link - https://www.dropbox.com/s/uwpkrb6uu7asx62/jquery.ui.rotatable.js?dl=0

Best

**Comment by Snorvarg** [comment]
Great, I got it working with the code I uploaded, having my own rotate handle. I have had some problems with creating the ontouch events the javascript way, but putting them inside the html as above seem to work..
